public class ClientIM extends javax.swing.JFrame {

    /** Creates new form ClientIM */
    public ClientIM() {
        initComponents();
        initClientIM();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterjFrame = new javax.swing.JFrame();
        ButtonjPanelR = new javax.swing.JPanel();
        OKjButtonR = new javax.swing.JButton();
        ClearjButtonR = new javax.swing.JButton();
        RContentjPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        ContentjPanel = new javax.swing.JPanel();
        LoginjPanel = new javax.swing.JPanel();
        LogoutjPanel = new javax.swing.JPanel();
        LoginjButton = new javax.swing.JButton();
        RegisterjButton = new javax.swing.JButton();
        jToolBar = new javax.swing.JToolBar();
        StatusjTextField = new javax.swing.JTextField();
        ActionjMenuBar = new javax.swing.JMenuBar();
        ActionjMenu = new javax.swing.JMenu();
        LogoutjMenuItem = new javax.swing.JMenuItem();

        RegisterjFrame.setMinimumSize(new java.awt.Dimension(300, 175));
        RegisterjFrame.setResizable(false);

        ButtonjPanelR.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        OKjButtonR.setText("jButton1");
        ButtonjPanelR.add(OKjButtonR);

        ClearjButtonR.setText("jButton2");
        ButtonjPanelR.add(ClearjButtonR);

        RegisterjFrame.getContentPane().add(ButtonjPanelR, java.awt.BorderLayout.SOUTH);

        RContentjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register To The Server", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        RContentjPanel.setPreferredSize(new java.awt.Dimension(300, 100));
        RContentjPanel.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setText("Name");
        jPanel2.add(jLabel1);

        jLabel3.setText("Username");
        jPanel2.add(jLabel3);

        jLabel2.setText("Password");
        jPanel2.add(jLabel2);

        RContentjPanel.add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jTextField1.setText("jTextField1");
        jPanel4.add(jTextField1);

        jTextField3.setText("jTextField1");
        jPanel4.add(jTextField3);

        jPasswordField1.setText("jPasswordField1");
        jPanel4.add(jPasswordField1);

        RContentjPanel.add(jPanel4, java.awt.BorderLayout.CENTER);

        RegisterjFrame.getContentPane().add(RContentjPanel, java.awt.BorderLayout.NORTH);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContentjPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout LoginjPanelLayout = new javax.swing.GroupLayout(LoginjPanel);
        LoginjPanel.setLayout(LoginjPanelLayout);
        LoginjPanelLayout.setHorizontalGroup(
            LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        LoginjPanelLayout.setVerticalGroup(
            LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        ContentjPanel.add(LoginjPanel, "loginCard");

        LogoutjPanel.setLayout(new java.awt.GridBagLayout());

        LoginjButton.setText("Login");
        LogoutjPanel.add(LoginjButton, new java.awt.GridBagConstraints());

        RegisterjButton.setText("Register");
        RegisterjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterjButtonActionPerformed(evt);
            }
        });
        LogoutjPanel.add(RegisterjButton, new java.awt.GridBagConstraints());

        ContentjPanel.add(LogoutjPanel, "logoutCard");

        getContentPane().add(ContentjPanel, java.awt.BorderLayout.CENTER);

        jToolBar.setRollover(true);

        StatusjTextField.setEditable(false);
        StatusjTextField.setFocusable(false);
        jToolBar.add(StatusjTextField);

        getContentPane().add(jToolBar, java.awt.BorderLayout.SOUTH);

        ActionjMenu.setText("Action");
        ActionjMenu.setEnabled(false);

        LogoutjMenuItem.setText("Logout");
        ActionjMenu.add(LogoutjMenuItem);

        ActionjMenuBar.add(ActionjMenu);

        setJMenuBar(ActionjMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterjButtonActionPerformed
        RegisterjFrame.setVisible(true);
    }//GEN-LAST:event_RegisterjButtonActionPerformed

    
    /**
     * Initialize IM client state
     */
    private void initClientIM() {
        SetLogout();
    }


    /**
     * Set IM client to logout state
     */
    private void SetLogout() {
        LogoutjPanel.setVisible(true);
        LoginjPanel.setVisible(false);
        ActionjMenuBar.setEnabled(false);
    }


    /**
     * Set IM client to login state
     */
    private void SetLogin() {
        LogoutjPanel.setVisible(false);
        LoginjPanel.setVisible(true);
        ActionjMenuBar.setEnabled(true);
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientIM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ActionjMenu;
    private javax.swing.JMenuBar ActionjMenuBar;
    private javax.swing.JPanel ButtonjPanelR;
    private javax.swing.JButton ClearjButtonR;
    private javax.swing.JPanel ContentjPanel;
    private javax.swing.JButton LoginjButton;
    private javax.swing.JPanel LoginjPanel;
    private javax.swing.JMenuItem LogoutjMenuItem;
    private javax.swing.JPanel LogoutjPanel;
    private javax.swing.JButton OKjButtonR;
    private javax.swing.JPanel RContentjPanel;
    private javax.swing.JButton RegisterjButton;
    private javax.swing.JFrame RegisterjFrame;
    private javax.swing.JTextField StatusjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables

}
