public class ClientIM extends javax.swing.JFrame {

    /** Creates new form ClientIM */
    public ClientIM() {
        initComponents();
        initClientIM();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentjPanel = new javax.swing.JPanel();
        LoginjPanel = new javax.swing.JPanel();
        LogoutjPanel = new javax.swing.JPanel();
        LoginjButton = new javax.swing.JButton();
        RegisterjButton = new javax.swing.JButton();
        jToolBar = new javax.swing.JToolBar();
        StatusjTextField = new javax.swing.JTextField();
        ActionjMenuBar = new javax.swing.JMenuBar();
        ActionjMenu = new javax.swing.JMenu();
        LogoutjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContentjPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout LoginjPanelLayout = new javax.swing.GroupLayout(LoginjPanel);
        LoginjPanel.setLayout(LoginjPanelLayout);
        LoginjPanelLayout.setHorizontalGroup(
            LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        LoginjPanelLayout.setVerticalGroup(
            LoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        ContentjPanel.add(LoginjPanel, "loginCard");

        LogoutjPanel.setLayout(new java.awt.GridBagLayout());

        LoginjButton.setText("Login");
        LogoutjPanel.add(LoginjButton, new java.awt.GridBagConstraints());

        RegisterjButton.setText("Register");
        LogoutjPanel.add(RegisterjButton, new java.awt.GridBagConstraints());

        ContentjPanel.add(LogoutjPanel, "logoutCard");

        getContentPane().add(ContentjPanel, java.awt.BorderLayout.CENTER);

        jToolBar.setRollover(true);

        StatusjTextField.setEditable(false);
        StatusjTextField.setFocusable(false);
        jToolBar.add(StatusjTextField);

        getContentPane().add(jToolBar, java.awt.BorderLayout.SOUTH);

        ActionjMenu.setText("Action");
        ActionjMenu.setEnabled(false);

        LogoutjMenuItem.setText("Logout");
        ActionjMenu.add(LogoutjMenuItem);

        ActionjMenuBar.add(ActionjMenu);

        setJMenuBar(ActionjMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Initialize IM client state
     */
    private void initClientIM() {
        SetLogout();
    }

    /**
     * Set IM client to logout state
     */
    private void SetLogout() {
        LogoutjPanel.setVisible(true);
        LoginjPanel.setVisible(false);
        ActionjMenuBar.setEnabled(false);
    }

    /**
     * Set IM client to login state
     */
    private void SetLogin() {
        LogoutjPanel.setVisible(false);
        LoginjPanel.setVisible(true);
        ActionjMenuBar.setEnabled(true);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientIM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ActionjMenu;
    private javax.swing.JMenuBar ActionjMenuBar;
    private javax.swing.JPanel ContentjPanel;
    private javax.swing.JButton LoginjButton;
    private javax.swing.JPanel LoginjPanel;
    private javax.swing.JMenuItem LogoutjMenuItem;
    private javax.swing.JPanel LogoutjPanel;
    private javax.swing.JButton RegisterjButton;
    private javax.swing.JTextField StatusjTextField;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables

}
